name: Lint

on:
    push:
        branches: ['*']
    pull_request:
        branches: ['*']

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: volta-cli/action@v4

            - name: NPM Install
              run: |
                  node --version
                  npm --version
                  npm i

            - name: Add minimal config
              run: |
                  echo "export default {};" > src/lib/data/config.js
                  echo "export const firebaseConfig = null;" > src/lib/data/firebase-config.js
                  echo "export const catalog = [];" > src/lib/data/catalog.js
                  echo "export default {}" > src/lib/data/contents.js

            - name: Run minimal build
              run: |
                  npx vite build

            - name: TypeScript/Svelte Check
              run: |
                  npm list --depth=0 typescript
                  npm run check

            - name: ESLint
              run: |
                  npm list --depth=0 eslint eslint-plugin-import prettier
                  npm run lint
